Repository 2025-Advanced-Capstone-Chaeum/FE, pull requests merged in 2025-06, with the labels that each got.

#133 Bugfix: 회원 상태관리 개선과 프로필 페이지 전체 기부내역 api를 통한 data로 변경후 UI 구성 #130
  public/sw.js
  src/app/(profile)/profile/donationhistory/page.tsx
  src/app/(profile)/profile/page.tsx
  src/app/welcome/page.tsx
  src/components/Cat.tsx
  src/components/profile/EditProfileModal.tsx
  src/components/profile/MyDonationList.tsx
  src/lib/api/axios.ts
  src/lib/api/user.ts
  src/lib/userData.ts
  src/store/userStore.ts
  src/utils/dateUtils.ts
Labels: 🐞 BugFix, 🔨 Refactor

#144 feature : 후기 목록/상세 조회 api 연결 (#131)
  src/app/(review)/review/[id]/page.tsx
  src/app/(review)/review/page.tsx
  src/app/(review)/review/write/[id]/page.tsx
  src/components/funding/ImageUpload.tsx
  src/components/funding/ReviewCard.tsx
  src/hooks/useFunding.tsx
  src/hooks/useReview.tsx
  src/lib/api/review.ts
Labels: 📬 API

#151 Styles/#147/chaeum 312
  next.config.ts
  pnpm-lock.yaml
  public/assets/images/paw.png
  public/assets/images/paw3.png
  public/sw.js
  src/app/(funding)/funding/page.tsx
  src/app/(funding)/funding/write/page.tsx
  src/app/(profile)/profile/recipient/complete/page.tsx
  src/app/globals.css
  src/app/landing/loginButton.tsx
  src/app/landing/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/welcome/page.tsx
  src/components/funding/FilterButton.tsx
  src/components/funding/NavigateToWriteButton.tsx
  src/components/funding/RegisterConfirmModal.tsx
  src/components/main/BottomMenu.tsx
  src/components/ui/Dropdown.tsx
  src/components/ui/NavigationBar.tsx
  src/components/ui/paw/PawPrints.tsx
  src/components/welcome/ClientWelcome.tsx
  src/lib/api/axios.ts
  src/lib/api/ocr.ts
Labels: 🔨 Refactor, 🎨 Styles

#153 styles : 기부자관련 UI 수정 (#150)
  package.json
  pnpm-lock.yaml
  src/app/(donation)/donation/complete/[id]/page.tsx
  src/app/(donation)/donation/reward/notify/page.tsx
  src/app/(donation)/donation/reward/page.tsx
  src/app/(funding)/funding/[id]/page.tsx
  src/app/(funding)/funding/page.tsx
  src/app/(funding)/funding/write/page.tsx
  src/app/(review)/review/[id]/page.tsx
  src/app/(review)/review/page.tsx
  src/components/funding/CampaignCard.tsx
  src/components/funding/ImageUpload.tsx
  src/components/funding/ReviewCard.tsx
  src/lib/api/funding.ts
  src/styles/styles.ts
Labels: 🎨 Styles

#156 styles: 기부보상관련 디자인 수정
  src/app/(funding)/funding/page.tsx
  src/app/(review)/review/page.tsx
  src/app/layout.tsx
  src/components/BodyBackgroundHandler.tsx
Labels: 🎨 Styles

#159 styles: 검토요청 메시지 제거 및 리뷰 레이아웃 추가
  src/app/(funding)/funding/register/page.tsx
  src/app/(review)/review/layout.tsx
Labels: 🔨 Refactor, 🎨 Styles

#161 styles: 드롭다운 버튼 너비 수정
  src/app/(funding)/funding/[id]/page.tsx
  src/components/ui/Dropdown.tsx
Labels: 🎨 Styles

#165 Api: 인벤토리 api flow에 맞게 수정 및 상호작용 api 연동 #135
  public/sw.js
  src/components/Cat.tsx
  src/components/inventory/ItemContainer.tsx
  src/components/main/BottomMenu.tsx
  src/components/profile/recipient/MyFundItem.tsx
  src/hooks/useInteraction.tsx
  src/lib/InteractionMenu.ts
  src/lib/api/inventory.ts
  src/lib/inventoryItems.ts
  src/store/catStore.ts
  src/store/interactionStore.ts
  src/types/itemTypes.ts
Labels: 📬 API

#168 Deploy: 배포 에러 해결 (#135)
  public/sw.js
  src/app/friends/[id]/page.tsx
  src/app/welcome/page.tsx
  src/components/inventory/ItemContainer.tsx
  src/components/main/BottomMenu.tsx
  src/components/main/ProgressBar.tsx
  src/store/interactionStore.ts
Labels: 🌏 Deploy

#169 BugFix : 초기 상태에서 interactive Bar 없어지는 문제, interactive item 갯수가 음수가 되는…
  public/sw.js
  src/app/welcome/page.tsx
  src/components/main/BottomMenu.tsx
  src/components/main/ProgressBar.tsx
  src/components/main/TopMenu.tsx
  src/components/ui/NavigationBar.tsx
  src/lib/api/funding.ts
  src/store/interactionStore.ts
Labels: 🐞 BugFix

#171 Bugfix : Fast Refetch Test
  src/app/(donation)/donation/reward/notify/page.tsx
  src/hooks/useDonation.tsx
  src/lib/InteractionMenu.ts
  src/lib/interactionIcons.ts
Labels: 🐞 BugFix

#173 후기 작성페이지 펀딩 정보 조회 및 UI 개선
  src/app/(review)/review/write/[id]/page.tsx
  src/components/funding/ReviewCard.tsx
  src/components/profile/ListContainer.tsx
  src/components/profile/recipient/MyFundList.tsx
Labels: 🔨 Refactor

#179 refactor: 수혜자 펀딩 목록 조회 개선
  src/app/(review)/review/page.tsx
  src/components/profile/recipient/MyFundItem.tsx
  src/components/profile/recipient/MyFundList.tsx
Labels: 🔨 Refactor
