Repository 2025-Advanced-Capstone-Chaeum/FE, pull requests merged in 2025-05, with the labels that each got.

#75 Feature: 환급 관련 페이지 (#68)
  pnpm-lock.yaml
  src/app/(refund)/refund/page.tsx
  src/app/(refund)/refund/result/page.tsx
  src/app/globals.css
  src/components/ConfirmButton.tsx
  src/components/ui/Dropdown.tsx
  src/utils/taxUtils.ts
Labels: ✨ Feature, 🎨 Styles

#74 Styles: 출석체크 페이지 , 앱 정보 페이지 (#69)
  public/assets/icons/footprint.svg
  src/app/about/page.tsx
  src/app/attendance/page.tsx
  src/components/AttendanceModal.tsx
  src/components/calendar/CalendarGrid.tsx
  src/components/calendar/CalendarHeader.tsx
  src/components/main/TopMenu.tsx
  src/components/ui/NavigationBar.tsx
  src/lib/attendance.ts
  src/lib/menuItems.ts
  src/utils/dateUtils.ts
Labels: ✨ Feature, 🎨 Styles

#78 Api/#76/chaeum 265
  pnpm-lock.yaml
  src/app/friends/page.tsx
  src/app/landing/loginButton.tsx
  src/components/NavigationBarWrapper.tsx
  src/lib/alarmMessage.ts
Labels: 📬 API

#80 Refactor: 전체 레이아웃 상단배치 (#77)
  src/app/(funding)/funding/page.tsx
  src/app/(profile)/profile/page.tsx
  src/app/(profile)/profile/recipient/register/page.tsx
  src/app/(review)/review/page.tsx
  src/app/alarm/page.tsx
  src/app/globals.css
  src/components/BackButton.tsx
  src/components/funding/FilterButton.tsx
  src/components/main/TopMenu.tsx
  src/components/ui/NavigationBar.tsx
Labels: 🔨 Refactor, 🎨 Styles

#81 Refactor: 추가 레이아웃 수정 (#77)
  src/app/(funding)/funding/page.tsx
  src/app/(funding)/funding/register/page.tsx
  src/app/(funding)/funding/write/page.tsx
  src/app/(profile)/profile/recipient/complete/page.tsx
  src/app/(review)/review/page.tsx
  src/app/page.tsx
  src/components/BackButton.tsx
  src/components/funding/FilterButton.tsx
  src/components/main/TopMenu.tsx
Labels: 🔨 Refactor, 🎨 Styles

#82 Refactor: 추추가 레이아웃 수정 (#77)
  src/app/(funding)/funding/write/page.tsx
  src/app/friends/page.tsx
  src/app/page.tsx
  src/components/friends/FriendsOrDonationButton.tsx
Labels: 🔨 Refactor, 🎨 Styles

#90 feature : 펀딩 등록, 펀딩 파일 업로드 api 연결 (#83)
  next.config.ts
  pnpm-lock.yaml
  src/app/(funding)/funding/write/page.tsx
  src/app/layout.tsx
  src/components/Providers.tsx
  src/components/funding/ImageUpload.tsx
  src/components/funding/RegisterConfirmModal.tsx
  src/components/ui/input.tsx
  src/components/ui/textarea.tsx
  src/hooks/useCreateFunding.tsx
  src/lib/api/axios.ts
  src/lib/api/funding.ts
  src/lib/queryClient.ts
Labels: 📬 API

#91 Fix: 빌드 에러 해결 (#83)
  pnpm-lock.yaml
  public/sw.js
Labels: 🐞 BugFix

#104 feature : 펀딩 전체 조회, 단건 조회 api 연결 (#103)
  next.config.ts
  public/sw.js
  src/app/(funding)/funding/[id]/page.tsx
  src/app/(funding)/funding/page.tsx
  src/app/(funding)/funding/write/page.tsx
  src/app/(profile)/profile/page.tsx
  src/components/funding/CampaignCard.tsx
  src/components/funding/RegisterConfirmModal.tsx
  src/hooks/useCreateFunding.tsx
  src/hooks/useFunding.tsx
  src/lib/api/funding.ts
  src/lib/api/profile.ts
Labels: 📬 API

#107 style : 펀딩 목록 및 상세 페이지 UI 수정 (#105)
  next.config.ts
  src/app/(funding)/funding/[id]/page.tsx
  src/app/(funding)/funding/page.tsx
  src/components/funding/CampaignCard.tsx
  src/components/funding/NavigateToWriteButton.tsx
  src/utils/dateUtils.ts
Labels: 🔨 Refactor, 🎨 Styles

#112 Feature: 고양이 정보 상태관리 #111
  next.config.ts
  public/sw.js
  src/app/page.tsx
  src/app/welcome/page.tsx
  src/hooks/useCat.tsx
  src/lib/api/cat.ts
  src/store/catStore.ts
  tailwind.config.ts
Labels: ✨ Feature

#115 Api: 아이템 카테고리별 인벤토리 목록 조회 #114
  public/assets/inventory/bed.svg
  public/assets/inventory/cap.svg
  public/assets/inventory/catTower.svg
  public/assets/inventory/necklace.svg
  public/assets/inventory/sunglasses.svg
  public/assets/inventory/tree.svg
  src/app/page.tsx
  src/app/welcome/page.tsx
  src/components/inventory/ItemContainer.tsx
  src/hooks/useInventory.tsx
  src/lib/api/inventory.ts
  src/lib/inventoryItems.ts
Labels: 📬 API

#118 feature : 결제, 기부 생성 api 연결 (#110)
  src/app/(donation)/donation/complete/page.tsx
  src/app/(funding)/funding/[id]/page.tsx
  src/app/(funding)/funding/page.tsx
  src/app/(funding)/funding/payment/page.tsx
  src/app/layout.tsx
  src/components/IamportSDKLoader.tsx
  src/components/funding/CampaignCard.tsx
  src/components/payment/SelectAmount.tsx
  src/components/payment/SelectPayMethod.tsx
  src/components/ui/NavigationBar.tsx
  src/hooks/useDonation.tsx
  src/hooks/usePayment.tsx
  src/lib/api/donation.ts
  src/lib/api/payment.ts
  src/lib/portone.ts
  src/store/donation.ts
  src/store/paymentStore.ts
Labels: 📬 API

#119 Api: 아이템 착용/ 해제 toggle api 연동 (#116)
  src/components/inventory/ItemContainer.tsx
  src/hooks/useInventory.tsx
  src/lib/api/inventory.ts
  src/lib/inventoryItems.ts
Labels: 📬 API

#120 feature : 기부 랜덤 보상 api 연결 (#117)
  next.config.ts
  src/app/(donation)/donation/complete/page.tsx
  src/app/(donation)/donation/reward/layout.tsx
  src/app/(donation)/donation/reward/notify/page.tsx
  src/hooks/useDonation.tsx
  src/lib/api/donation.ts
  src/lib/donationReward.ts
  src/lib/interactionIcons.ts
Labels: 📬 API

#125 feature : 펀딩 리뷰 생성 api 연결 (#121)
  src/app/(donation)/donation/complete/page.tsx
  src/app/(funding)/funding/[id]/page.tsx
  src/app/(funding)/funding/page.tsx
  src/app/(funding)/funding/payment/page.tsx
  src/app/(funding)/funding/write/page.tsx
  src/app/(review)/review/write/[id]/page.tsx
  src/components/funding/ImageUpload.tsx
  src/components/funding/ReviewCard.tsx
  src/components/profile/recipient/MyFundItem.tsx
  src/components/profile/recipient/MyFundList.tsx
  src/hooks/useFunding.tsx
  src/hooks/useReview.tsx
  src/lib/api/review.ts
Labels: 📬 API, 🐞 BugFix

#127 Api: 착용중인 인벤토리 api 연동// 인벤토리 api와 UI 동기화// 로컬에서 미들웨어 비활성화 // build시 navigationBar 에서의 warning 해결 #113
  next.config.ts
  package.json
  pnpm-lock.yaml
  public/sw.js
  src/app/inventory/page.tsx
  src/app/landing/page.tsx
  src/app/page.tsx
  src/app/welcome/page.tsx
  src/components/Cat.tsx
  src/components/inventory/ItemContainer.tsx
  src/components/ui/NavigationBar.tsx
  src/hooks/useDonation.tsx
  src/hooks/useInventory.tsx
  src/lib/api/axios.ts
  src/lib/api/inventory.ts
  src/lib/inventoryItems.ts
  src/middleware.ts
  src/store/catStore.ts
Labels: 📬 API, 🐞 BugFix, ✨ Feature, ⚙ Setting, 🎨 Styles

#132 fix : 결제 리다이렉트 경로 변경 (#129)
  package.json
  pnpm-lock.yaml
  src/app/(funding)/funding/payment/page.tsx
  src/components/funding/ImageUpload.tsx
Labels: 🐞 BugFix

#136 fix: 결제 로직 변경 및 기부/결제 생성 에러 해결
  next.config.ts
  src/app/(donation)/donation/complete/[id]/page.tsx
  src/app/(donation)/donation/loading/page.tsx
  src/app/(funding)/funding/payment/page.tsx
  src/lib/api/donation.ts
  src/lib/portone.ts
  src/store/paymentStore.ts
Labels: 🐞 BugFix

#137 fix: Suspense로 서버, 클라이언트 컴포넌트 분리 (#129)
  src/app/(donation)/donation/loading/page.tsx
  src/components/DonationLodaingClient.tsx
Labels: 🐞 BugFix

#138 fix: 결제 관련 주석, 로그 제거 (#129)
  src/app/(donation)/donation/loading/page.tsx
  src/components/DonationLodaingClient.tsx
  src/store/paymentStore.ts
Labels: 🐞 BugFix

#109 feature : 펀딩 조건별 조회 api 연결 (#108)
  src/app/(funding)/funding/page.tsx
  src/components/funding/FilterButton.tsx
  src/hooks/useFunding.tsx
  src/lib/api/funding.ts
Labels: 📬 API, 🎨 Styles
